[0m14:22:13.769751 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11250ba70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112527fe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112527f80>]}


============================== 14:22:13.772195 | e53fb1a8-f5dd-4097-8019-f304e674081c ==============================
[0m14:22:13.772195 [info ] [MainThread]: Running with dbt=1.7.9
[0m14:22:13.772465 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/lou/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:22:20.605954 [debug] [MainThread]: Starter project path: /opt/anaconda3/envs/dbt2/lib/python3.12/site-packages/dbt/include/starter_project
[0m14:22:20.610856 [info ] [MainThread]: 
Your new dbt project "projet_live" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:22:20.611143 [info ] [MainThread]: Setting up your profile.
[0m14:22:31.690142 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102982d20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1130996d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1130b9850>]}
[0m14:22:31.690537 [debug] [MainThread]: Flushing usage events
[0m16:55:34.529387 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10856c800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10859bf80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085d42f0>]}


============================== 16:55:34.532221 | 24b24969-cc65-473e-8001-ad63a3fc17d0 ==============================
[0m16:55:34.532221 [info ] [MainThread]: Running with dbt=1.7.9
[0m16:55:34.532523 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/lou/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:55:34.532779 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/lou/Documents/GitHub/DBT2/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:55:34.533986 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10856c800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085d4140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085d5fd0>]}
[0m16:55:34.534167 [debug] [MainThread]: Flushing usage events
[0m09:34:31.268902 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114a00560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114a33710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114a332c0>]}


============================== 09:34:31.271516 | 7c33d5fc-097a-4dcd-a19e-39452b55de59 ==============================
[0m09:34:31.271516 [info ] [MainThread]: Running with dbt=1.7.9
[0m09:34:31.271801 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/lou/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:34:42.554946 [info ] [MainThread]: A project called projet_live already exists here.
[0m09:34:42.692176 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 11.44707, "process_user_time": 0.805284, "process_kernel_time": 0.124371, "process_mem_max_rss": "104267776", "process_in_blocks": "0", "process_out_blocks": "0"}
[0m09:34:42.692827 [debug] [MainThread]: Command `dbt init` succeeded at 09:34:42.692646 after 11.45 seconds
[0m09:34:42.693297 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1139032c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1142fc920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114851be0>]}
[0m09:34:42.693744 [debug] [MainThread]: Flushing usage events
[0m19:48:09.858870 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118cc6030>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118cfba10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118cfb4d0>]}


============================== 19:48:09.861301 | dd7450c0-d6e6-4ca6-83b9-97a5e82a6e61 ==============================
[0m19:48:09.861301 [info ] [MainThread]: Running with dbt=1.7.9
[0m19:48:09.861577 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/lou/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m19:48:09.861815 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/lou/Documents/GitHub/DBT2/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:48:09.871095 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.033703208, "process_user_time": 0.831747, "process_kernel_time": 0.174742, "process_mem_max_rss": "104660992", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m19:48:09.871385 [debug] [MainThread]: Command `dbt run` failed at 19:48:09.871320 after 0.03 seconds
[0m19:48:09.871565 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118a15730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118cfb4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118cfb800>]}
[0m19:48:09.871738 [debug] [MainThread]: Flushing usage events
[0m19:57:58.916568 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106c8f8f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067401a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cc7620>]}


============================== 19:57:58.918959 | 07a3a60b-9ce1-4cc1-bf9d-aca21f6f1aaa ==============================
[0m19:57:58.918959 [info ] [MainThread]: Running with dbt=1.7.9
[0m19:57:58.919219 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/lou/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:57:58.919456 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/lou/Documents/GitHub/DBT2/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:57:58.920677 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.02656275, "process_user_time": 0.672029, "process_kernel_time": 0.084525, "process_mem_max_rss": "103956480", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m19:57:58.920899 [debug] [MainThread]: Command `dbt run` failed at 19:57:58.920841 after 0.03 seconds
[0m19:57:58.921049 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cc78c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cc7ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cc7680>]}
[0m19:57:58.921196 [debug] [MainThread]: Flushing usage events
